services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: celery -A foodtracker_app.notifications.celery_worker.celery_app worker -l INFO -P gevent
    volumes:
      - ./foodtracker:/app
    env_file:
      - ./foodtracker/.env
    depends_on:
      - redis
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: uvicorn foodtracker_app.main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude "*celerybeat-schedule*" --reload-exclude "*beat_db.sqlite3*"
    ports:
      - "8000:8000"
    volumes:
      - ./foodtracker:/app
    env_file:
      - ./foodtracker/.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: celery -A foodtracker_app.notifications.celery_worker.celery_app beat --loglevel=info
    volumes:
      - ./foodtracker:/app
    env_file:
      - ./foodtracker/.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data:
