FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y libmagic1 libgdbm-dev && rm -rf /var/lib/apt/lists/*

COPY foodtracker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

CMD ["uvicorn", "foodtracker_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
