"""Add pantry_invitations table

Revision ID: 170691402920
Revises: abfc72e33bee
Create Date: 2025-06-28 16:11:24.687471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "170691402920"
down_revision: Union[str, None] = "abfc72e33bee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pantry_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pantry_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["pantry_id"], ["pantries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pantry_invitations_id"), "pantry_invitations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pantry_invitations_token"),
        "pantry_invitations",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pantry_invitations_token"), table_name="pantry_invitations")
    op.drop_index(op.f("ix_pantry_invitations_id"), table_name="pantry_invitations")
    op.drop_table("pantry_invitations")
    # ### end Alembic commands ###
