"""Add financial_stats table

Revision ID: 3045e9b2e07e
Revises: 80fbcde586c4
Create Date: 2025-06-15 17:09:25.953027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3045e9b2e07e'
down_revision: Union[str, None] = '80fbcde586c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('saved_value', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('wasted_value', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_stats')
    # ### end Alembic commands ###
