"""Add quantity columns to products table

Revision ID: 363e8148e13a
Revises: b5becdb81269
Create Date: 2025-06-14 05:09:25.140503

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "363e8148e13a"
down_revision: Union[str, None] = "b5becdb81269"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("quantity_initial", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("quantity_current", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_column("products", "is_used")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("products", "quantity_current")
    op.drop_column("products", "quantity_initial")
    # ### end Alembic commands ###
