"""add quiantity_wasted to products

Revision ID: 401d0556b5aa
Revises: 363e8148e13a
Create Date: 2025-06-14 07:02:55.801340

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "401d0556b5aa"
down_revision: Union[str, None] = "363e8148e13a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("quantity_wasted", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "quantity_wasted")
    # ### end Alembic commands ###
