"""Add notification preference to user

Revision ID: 4adab9e091e7
Revises: 170691402920
Create Date: 2025-06-28 20:59:29.278910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4adab9e091e7"
down_revision: Union[str, None] = "170691402920"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "send_expiration_notifications",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "send_expiration_notifications")
    # ### end Alembic commands ###
