"""Create categories table

Revision ID: abfc72e33bee
Revises: ddea1c49754b
Create Date: 2025-06-28 15:14:58.719921

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "abfc72e33bee"
down_revision: Union[str, None] = "ddea1c49754b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
