"""Set server-side default for user created_at

Revision ID: b5becdb81269
Revises: 279ecf3961aa
Create Date: 2025-06-13 16:45:16.579598

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b5becdb81269"
down_revision: Union[str, None] = "279ecf3961aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
