"""Implement hybrid product model

Revision ID: ce519e99a81d
Revises: 401d0556b5aa
Create Date: 2025-06-15 11:27:28.685744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce519e99a81d"
down_revision: Union[str, None] = "401d0556b5aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.add_column("products", sa.Column("unit", sa.String(length=10), nullable=False))
    op.add_column(
        "products",
        sa.Column("initial_amount", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("current_amount", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.drop_column("products", "quantity_wasted")
    op.drop_column("products", "quantity_current")
    op.drop_column("products", "quantity_initial")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "quantity_initial",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "quantity_current",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "quantity_wasted",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("products", "current_amount")
    op.drop_column("products", "initial_amount")
    op.drop_column("products", "unit")
    op.drop_column("products", "price")
    # ### end Alembic commands ###
