"""Add cascade delete to users and pantries

Revision ID: ddea1c49754b
Revises: c614d36f429e
Create Date: 2025-06-28 07:25:52.717360

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ddea1c49754b"
down_revision: Union[str, None] = "c614d36f429e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("pantries_owner_id_fkey"), "pantries", type_="foreignkey")
    op.create_foreign_key(
        None, "pantries", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("pantry_users_user_id_fkey"), "pantry_users", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("pantry_users_pantry_id_fkey"), "pantry_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "pantry_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "pantry_users", "pantries", ["pantry_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pantry_users", type_="foreignkey")
    op.drop_constraint(None, "pantry_users", type_="foreignkey")
    op.create_foreign_key(
        op.f("pantry_users_pantry_id_fkey"),
        "pantry_users",
        "pantries",
        ["pantry_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("pantry_users_user_id_fkey"), "pantry_users", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "pantries", type_="foreignkey")
    op.create_foreign_key(
        op.f("pantries_owner_id_fkey"), "pantries", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
