name: tests

on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r foodtracker/requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: test
          DATABASE_URL:
            sqlite+aiosqlite:///:memory:
          SMTP_HOST: localhost
          SMTP_PORT: 587
          SMTP_USER: test@test.com
          SMTP_PASSWORD: test
          MAIL_FROM: noreply@test.com
          MAIL_FROM_NAME: Test Mail
          DEMO_MODE: true
          GOOGLE_CLIENT_ID: test
          GOOGLE_CLIENT_SECRET: test
          GITHUB_CLIENT_ID: test
          GITHUB_CLIENT_SECRET: test
          RECAPTCHA_SECRET_KEY: test
          FRONTEND_URL: http://localhost:5173
          REDIS_URL: redis://localhost:6379
          SKIP_REDIS: true
          TESTING: true
          IS_PRODUCTION: true
        run: |
          pytest -q
